server:
  port: 8888

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
    user:
      name: admin
      password: admax

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: myrealm
  resource: localhost8888
  ssl-required: none
  public-client: true
  security-constraints[0].authRoles[0]: ROLE_VIEWER
  security-constraints[0].securityCollections[0].patterns[0]: /*
  principal-attribute: preferred_username

security:
  enabled: true
  oauth2:
    client:
      registration:
        keycloak:
          client-id: localhost8888
          client-secret: keycloak
          clientName: keyCloak
          authorization-grant-type: authorization_code
          redirectUriTemplate: '{baseUrl}/login/oauth2/code/{registrationId}'
          scope:
            - openid
            - profile
            - email

      provider:
        keycloak:
          authorization-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/auth
          token-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/token
          user-info-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/userinfo
          jwk-set-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/certs
          user-name-attribute: preferred_username

management:
  security:
    enabled: false