server:
  port: 8888

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.9115f1fd186999f0
            client-secret: 21358bff0f3eca83bf0b81f3f901eed0eb813f9c
          keycloak:
            client-id: localhost8888
            client-secret: keycloak
            clientName: keyCloak
            authorization-grant-type: authorization_code
            redirectUriTemplate: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            authorization-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/auth
            token-uri:         http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/token
            user-info-uri:     http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/userinfo
            jwk-set-uri:       http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/certs
            user-name-attribute: preferred_username
