server:
  port: 8888

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
    user:
      name: admin
      password: admax

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: localhost8888
  resource: localhost8888
  ssl-required: none
  public-client: true